### ISSUE TITLE
Authentication Failure from android agent after 1-2 days of enrollment

### ISSUE THREAD

**Issue by paulthomas404** [wso2/cdmf-agent-android#198]
After 1-2 days of enrolling the android device, the android agent shows Authentication Failure. Would it be a good idea to increase the RefreshTokenValidityPeriod value as mentioned in #109 and workaround this issue? So then that means that we'd have to give it a very high value which makes the RenewRefreshToken provision useless.

**version: wsiot 3.1.0**

I've also tried changing the RefreshTokenValidityPeriod value to 10,00,000 and restarted iots and have rebooted the client - but the issue persists.
Setting RenewRefreshTokenForRefreshGrant to false also didn't work for me.

Please find below my client logs for the same:

12-03 09:28:49.960 8526 8526 E AgentApplication: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wso2.iot.agent/org.wso2.iot.agent.activities.AuthenticationActivity}: java.lang.StringIndexOutOfBoundsException: length=5; regionStart=0; regionLength=-1
12-03 09:28:49.960 8526 8526 E AgentApplication: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
12-03 09:28:49.960 8526 8526 E AgentApplication: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
12-03 09:28:49.960 8526 8526 E AgentApplication: at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-03 09:28:49.960 8526 8526 E AgentApplication: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
12-03 09:28:49.960 8526 8526 E AgentApplication: at android.os.Handler.dispatchMessage(Handler.java:102)
12-03 09:28:49.960 8526 8526 E AgentApplication: at android.os.Looper.loop(Looper.java:154)
12-03 09:28:49.960 8526 8526 E AgentApplication: at android.app.ActivityThread.main(ActivityThread.java:6121)
12-03 09:28:49.960 8526 8526 E AgentApplication: at java.lang.reflect.Method.invoke(Native Method)
12-03 09:28:49.960 8526 8526 E AgentApplication: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-03 09:28:49.960 8526 8526 E AgentApplication: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-03 09:28:49.960 8526 8526 E AgentApplication: Caused by: java.lang.StringIndexOutOfBoundsException: length=5; regionStart=0; regionLength=-1
12-03 09:28:49.960 8526 8526 E AgentApplication: at java.lang.String.substring(String.java:1931)
12-03 09:28:49.960 8526 8526 E AgentApplication: at org.wso2.iot.agent.activities.AuthenticationActivity.onCreate(AuthenticationActivity.java:160)
12-03 09:28:49.960 8526 8526 E AgentApplication: at android.app.Activity.performCreate(Activity.java:6723)
12-03 09:28:49.960 8526 8526 E AgentApplication: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
12-03 09:28:49.960 8526 8526 E AgentApplication: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
12-03 09:28:49.960 8526 8526 E AgentApplication: ... 9 more
12-03 09:28:49.961 8526 8526 I art : System.exit called, status: 2
12-03 09:28:49.961 8526 8526 I AndroidRuntime: VM exiting with result code 2, cleanup skipped.
12-03 09:28:50.073 3226 3388 I ActivityManager: Process org.wso2.iot.agent (pid 8526) has died

**Comment by paulthomas404** [comment]
Sorry, I just saw that the tenantedUserName.substring issue was fixed with v3.1.25 release.
